@startuml
'https://plantuml.com/component-diagram

TCPChannel --> [TcpLength]
[TcpLength] --> [ShakeTimeout]
[ShakeTimeout] --> [HandShake]

UDPServer --> [UDPMultiplex]
[UDPMultiplex] --> [MOTDHandler]
[MOTDHandler] --> [HandShake]

[TcpLength] --> [MultiplexHandler]
[UDPMultiplex] --> [MultiplexHandler]

[MultiplexHandler] - [PacketHandler]
[MultiplexHandler] --> [ReadTimeout]
[ReadTimeout] --> [StreamableHandler]
[StreamableHandler] --> [BossHandler]
@enduml